name: Build and test

on:
  pull_request: 
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with: { go-version: 1.25.3 }

      - name: Build
        run: go build -o hyprls cmd/hyprls/main.go

      - name: Run tests
        run: go test
