name: Update nix inputs

on:
  workflow_dispatch:
  schedule:
    - cron: '51 2 * * 0'

jobs:
  update:
    name: inputs
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: DeterminateSystems/nix-installer-action@00199f951aeb9404028a6e4b95ad42546f73296a # main
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4
      - name: Update inputs
        run: just update-nix-inputs

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: '⬆️ Nix: update inputs'
