name: Update submodules

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 2 * * * # every day at 2 am

jobs:
  pull:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: ConorMacBride/install-package@3e7ad059e07782ee54fa35f827df52aae0626f30 # v1
        with:
          apt: moreutils
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - run: just check-for-hyprland-updates

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8

        with:
          commit-message: 🍱 Update parser data from wiki
          title: Update data from wiki
          branch: update-from-wiki
