name: Update nix inputs

on:
  workflow_dispatch:
  schedule:
    - cron: '51 2 * * 0'

jobs:
  update:
    name: inputs
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: DeterminateSystems/nix-installer-action@00199f951aeb9404028a6e4b95ad42546f73296a # main
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4
      - name: Update inputs
        run: just update-nix-inputs

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: '⬆️ Nix: update inputs'
